let qust = document.querySelector(".qust");
let opt1 = document.querySelector("#opt1");
let opt2 = document.querySelector("#opt2");
let opt3 = document.querySelector("#opt3");
let opt4 = document.querySelector("#opt4");
let btn = document.querySelector(".new");

console.log(qust.innerText);

opt1.style.display = "none";
qust.style.display = "none";

let questions = [
    "What is JavaScript, and how is it different from Java?",
    "How do you declare a variable in JavaScript?",
    "What are the different types of data types available in JavaScript?",
    "What is the difference between let, var, and const?",
    "How do you write comments in JavaScript?",
    "What are template literals in JavaScript?",
    "How can you convert a string to a number in JavaScript?",
    "What is the difference between == and ===?",
    "What is the purpose of the typeof operator in JavaScript?",
    "What are JavaScript closures?",
    "How do you define a function in JavaScript?",
    "What is an anonymous function in JavaScript?",
    "What are arrow functions, and how are they different from regular functions?",
    "What is the purpose of the this keyword in JavaScript?",
    "How do you create objects in JavaScript?",
    "What is object destructuring in JavaScript?",
    "What is the difference between null and undefined?",
    "What is the use of the try...catch block in JavaScript?",
    "How do you create an array in JavaScript?",
    "What are higher-order functions in JavaScript?",
    "What is the difference between map, filter, and reduce in JavaScript?",
    "How does forEach() differ from map() in JavaScript?",
    "What are promises in JavaScript?",
    "How do you handle asynchronous code in JavaScript?",
    "What is the purpose of the async and await keywords?",
    "How does the JavaScript event loop work?",
    "What is a callback function in JavaScript?",
    "What is event delegation in JavaScript?",
    "How do you add an event listener to an element in JavaScript?",
    "What is the difference between preventDefault() and stopPropagation()?",
    "What is the DOM in JavaScript?",
    "How do you select elements in the DOM using JavaScript?",
    "How do you manipulate the DOM in JavaScript?",
    "What is the difference between innerHTML and textContent?",
    "How do you handle form submissions using JavaScript?",
    "What is local storage in JavaScript, and how do you use it?",
    "What is the difference between local storage and session storage?",
    "How do you make an HTTP request using JavaScript?",
    "What is the Fetch API in JavaScript?",
    "How do you use setTimeout and setInterval in JavaScript?",
    "What are modules in JavaScript, and how do you export and import them?",
    "What is hoisting in JavaScript?",
    "What is the purpose of the new keyword in JavaScript?",
    "What is the difference between function expressions and function declarations?",
    "What is a prototype in JavaScript?",
    "How do you implement inheritance in JavaScript?",
    "What are the different types of loops available in JavaScript?",
    "How do you handle errors in JavaScript?",
    "What is the difference between synchronous and asynchronous code?",
    "What is a promise chain in JavaScript?"
];

let answere = [
    "Scripting",
    "var/let/const",
    "Primitive",
    "Scope",
    "Comments",
    "Backticks",
    "Number()",
    "Strict",
    "Type",
    "Closure",
    "Function",
    "Callback",
    "Arrow",
    "Context",
    "Literal",
    "Destructuring",
    "Value",
    "Error-handling",
    "Array",
    "Functions",
    "Iteration",
    "Side-effects",
    "Promise",
    "Async",
    "Await",
    "Loop",
    "Callback",
    "Delegation",
    "addEventListener()",
    "Prevent/Stop",
    "DOM",
    "Selectors",
    "Manipulation",
    "Content",
    "Submission",
    "Storage",
    "Duration",
    "AJAX",
    "Fetch",
    "Timer",
    "Modules",
    "Hoisting",
    "Constructor",
    "Expression",
    "Prototype",
    "Inheritance",
    "Loops",
    "Catch",
    "Sync/Async",
    "Chain"
];

